### ISSUE TITLE
Don't rename mednafen_psx*_libretro.so to beetle_psx_libretro.so

### ISSUE THREAD

**Issue by crocket** [stefan-gr/abendbrot#104]
RetroArch core info database doesn't recognize beetle_psx_libretro.

**Comment by stefan-gr** [comment]
Thanks, it seems like they dropped the info file. Regardless of that, I'm thinking of renaming this ebuild to mednafen again, just like the others and make it so that hw and sw cores are install-able at the same time. But that will also have to wait until I have gentoo again. I don't want to make too many deep changes without being able to test them.

**Comment by crocket** [comment]
`mednafen_psx_hw_libretro.info` is installed by `games-emulation/libretro-info`.
It feels wrong to rename `mednafen_psx_hw_libretro.so` to `mednafen_psx_libretro.so`
