### ISSUE TITLE
retroarch dispmanx use flag

### ISSUE THREAD

**Issue by barbudreadmon** [stefan-gr/abendbrot#41]
It would be nice to add the dispmanx use flag.
On raspberries, kms/X/wayland should not be required use flags since you can use dispmanx (a layer that accesses the video compositing machinery of the raspberry VideoCore gpu)

**Comment by stefan-gr** [comment]
I can't test this but it complained about missing bcm_host.h so I added media-libs/raspberrypi-userland*-bin to it and did some flag appending. Could you tell me if that did it?

**Comment by barbudreadmon** [comment]
Can't build this, raspberrypi-userland and raspberrypi-userland-bin exclude each other.

**Comment by barbudreadmon** [comment]
My bad, they actually don't, but they are basically the same thing built in different folders, you don't need both.

**Comment by stefan-gr** [comment]
I forgot to but them besides a ||, try it now.

**Comment by barbudreadmon** [comment]
It builds fine, but the dispmanx video driver crash at the moment.
Seems to me i got things wrong, and retroarch on raspberry require none of those use flag to work, it will detect if you have a videocore gpu at configure time (i checked, no switch for the command line), and add some settings to the config.mk, i noticed the following lines mentioning the videocore libraries : 

```
INCLUDE_DIRS =  -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux -I./decompress/7zip/
LIBRARY_DIRS =  -L/opt/vc/lib -L/opt/vc/lib/GL
EGL_LIBS = -lEGL -lEGL -lGLESv2 -lbcm_host -lvcos -lvchiq_arm
SDL2_CFLAGS = -D_REENTRANT -I/usr/include/SDL2 -I/opt/vc/include -I/opt/vc/include/interface/vcos/pthreads -I/opt/vc/include/interface/vmcs_host/linux
```

My guess :
- dispmanx should be an alternative to sdl / sdl2 / vulkan / opengl, not to kms / x / wayland
- We should have a "videocore" use flag, which would be the alternative to kms / x / wayland , either a "blank" one who would do nothing except being there to avoid having to build kms or x or wayland on a system that doesn't need it, or an useful one who would edit config.mk : remove mentions to vc, bcm_host and such if disabled (so we would not build videocore support if we don't want it, which would make sense only if we want to use the new drm/kms driver for raspberry). Actually the first choice makes more sense : it is less work, someone who want to use the new driver wouldn't build the old one, avoiding the autodetect of bcm_host/vc stuff by retroarch, someone who don't want the new driver would want the old one.

By the way, since dispmanx is videocore specific, and videocore is rpi specific, it could be a good thing to require videocore when dispmanx is enabled, and mask both on non-arm arch (or disallow them ? i don't know how to mask use flags for specific arch in an overlay)

**Comment by stefan-gr** [comment]
I implemented some changes.
* videocore, set HAVE_VIDEOCORE=yes
 * This enables/disables the opt/vc lib/includes
 * It also disables forced -lEGL -lGLESv2
* dispmanx requires videocore but not the other way around
 * Are there more drivers for videocore or is dispmanx synonymous with videocore? We could just throw them into one flag since it looks like both are required for each other to work.

I tried masking some packages in the past for the overlay but it didn't seem to get picked up by portage, but eix showed it correctly. I will fiddle with this again and try to get it working.

**Comment by stefan-gr** [comment]
Doesn't work, I can only mask for everyone but I can't unmask for a specific arch. I'm thinking of prefixing those flags with arm_*.

**Comment by barbudreadmon** [comment]
dispmanx is not necessary, if you build for videocore and disable dispmanx, it works through the gl(es) driver

**Comment by barbudreadmon** [comment]
Seems to work, would be nice to backport those changes to the 1.3.6 ebuild

**Comment by stefan-gr** [comment]
Sounds good, I added arm and arm64 to USE_REQUIRED for them, that should do it.

**Comment by barbudreadmon** [comment]
Shouldn't your condition be 
`dispmanx? ( videocore? ( arm || arm64 ) )`
?
Also, i'm pretty sure raspberry-userland don't work on arm64 at the moment (and raspberry team don't intend to add arm64 support from what i understood), so : 
`dispmanx? ( videocore? ( arm ) )`
?

**Comment by stefan-gr** [comment]
Ah, I see.
I read somewhere that rpi3 is built with a 64bit cpu so I though of future proofing it. But it seems confusing, in retrospect, to imply that arm64 actually works.

Doesn't dispmanx depend on videocore? A question mark would make videocore depend on arm only when dispmanx is set and also NOT set videocore as dependency on dispmanx, since it's just a test. The syntax for this is quite confusing but should work fine, I tested it with amd64 instead of arm on my machine.

I will change the arm64 thing for now. That should also make the condition readable again.
