### ISSUE TITLE
Drop vulkan-base in favour or tree's vulkan-loader

### ISSUE THREAD

**Issue by chewi** [stefan-gr/abendbrot#50]
These appear to be the same thing and RetroArch builds against the latter. Unfortunately I get an error when starting RetroArch under RADV regardless of which package I use but that's another story!

On a side note, this overlay is really great work, thank you very much. I'd love to get this in the tree but obviously it's a lot of packages with some lacking proper releases. I'm pretty stretched as it is but maybe we could work out some kind of proxy maintainership. I don't usually like that option but you clearly know what you're doing here. Unless you'd like to become a dev, of course. :wink:

**Comment by stefan-gr** [comment]
Thanks for the heads up and the kind words for this gobbled together overlay @chewi.

I though about trying to maintain ebuilds a few years ago and noticed that I barely have enough time to make sure things work properly in this overlay and most of my ebuild writing knowledge got picked up along the way so it isn't on par with what I would expect to get from the tree.

I wouldn't mind helping getting retroarch and co into shape for it, though. Many things have to be fixed, removed and tested since some assumptions made in the ebuilds could no longer be valid, I got lazy and didn't even include proper dependencies or repoman will not open the gates to commit.

I have read the proxy maintainer wiki and must confess to be a little overwhelmed by the requirements needed to get into it, there are multiple new grounds for me to overcome since I'm not a programmer/artist or office worker and usually don't do collaborative things over various channels. I also like that I don't feel too forced to take care of abendbrot issues, though I try to fix them asap. It's more of a pastime at this point

I'm sorry that I can't help the gentoo community more by becoming a proper dev/proxy maintainer but I hope that this overlay provides some sort of stopgap/compromise for users.

**Comment by barbudreadmon** [comment]
Nice to see there is proper vulkan handling in gentoo at last :)

**Comment by chewi** [comment]
It's cool but don't sell yourself short. Maybe I'm not aware of the finer details but I couldn't see anything wrong and I've certainly seen a hell of a lot worse. Keep it up. :smile:
