### ISSUE TITLE
"nvidia-cg-toolkit" as a dependency

### ISSUE THREAD

**Issue by PureTryOut** [stefan-gr/abendbrot#54]
Is this really required? I use Intel Mesa drivers on my laptop and AMD Mesa drivers on my desktop, and I don't see why I need a NVIDIA package to run RetroArch. Can I remove this dependency somehow (I guess by removing shaders?) without stuff breaking?

**Comment by stefan-gr** [comment]
retroarch doesn't need shaders to work correctly. Most people expect them to be available, though.

It's a non gpu specific framework for the opengl shaders, I have it set as default for maximum compatibility and retroarch needs _nvidia-cg-toolkit_ for that to work.

You can disable that dependency with _"-cg"_ but it then needs _"glsl"_ or _"vulkan"_, disabling _"shaders"_ removes them completely. _"glsl"_ converts the cg shaders with retroarch-cg2glsl that's why _common-shaders_ still depends on it at build time.

Please keep in mind that upstream develops the shaders only for cg(opengl) and vulkan. The converted shaders aren't guaranteed to work at all, but mostly do. I just found a handful that don't work.

Do you think it's better to drop that as a default? I had mostly usefulness in mind when setting the dependencies but I also understand not wanting more unnecessary blobs as default.

**Comment by PureTryOut** [comment]
Aah, adding `vulkan` did indeed remove the need, thanks for that.

In my opinion I would try to stay away from blobs as much as possible, and only add them if actually required. Since `glsl` and `vulkan` seem to do the job as well like you said, I would use either one of those as default instead. For the compatibility issues I would say `vulkan`, but that might not be supported by older GPU's (but any modern laptop or desktop will have no problems with it). Do note that `media-libs/vulkan-loader` then becomes a dependency.

**Comment by stefan-gr** [comment]
Heh, my card is too old for vulkan so I'm fishing blind with the vulkan support at the moment. I have heard stories of shaders from it not working on not vulkan enabled cores and such things so I'm not sure how to test all that before I wait for the inevitable price drop after the vega announcement.

Though, I do know that using opengl is the preferred setup upstream for desktop use and I myself had some not so nice run-ins with gles bugs (sorry I meant `gles2,gles3 `and not `glsl` above, thats the name for the shaderfiles). Not to mention I had to nuke my retroarch cfg every time I changed between opengl/X and gles/wayland. I hope it isn't that dramatic with vulkan.

I'm more on the end of dropping `shaders` as default and to put some instructions/warnings as a pkg_pretend check when that flag gets enabled with `cg`.

I will look into that next week since have burned all my alone time with the recent ebuild changes  :disappointed:.

**Comment by PureTryOut** [comment]
But it's holiday! You're not supposed to waste all your time on stuff like this!

Dropping `shaders` as default seems like the best course of action then indeed.

**Comment by jansegre** [comment]
@PureTryOut I just happen to come across this, and I don't see whats wrong with `nvidia-cg-toolkit` as a dependency here. I think it makes as much sense to keep `shaders` as is having `cores`, `assets`, `database` and the like.

There's just a detail I don't get is why `nvidia-cg-toolkit` is required when `cg` is used, from what I understand `cg` means you're GPU supports loading `.cg` shaders so you wouldn't need `nvidia-cg-toolkit` which only serves to compile `.cg` shaders to `.glsl`. Since my graphics are Intel/AMD hybrid I can't test this.

Another possibility, albeit more complex, would be making some `virtual/common-shaders` and have two packages `games-emulation/common-shaders` and `games-emulation/common-shaders-bin` provide them, and `games-emulation/common-shaders-bin` simply download the official `.glsl` shaders (which are just the upstream `.cg` shaders compiled on the libretro build servers). So some sort of scheme like that could be used to optionally skip depending on `nvidia-cg-toolkit`, but that's too much IMO.

Anyhow, I think `shaders` should be kept as default (as much as `cores` and others), and I suggest simply _using_ `-shaders` in that case.

What do you think?

**Comment by PureTryOut** [comment]
It's mainly that I disagree with having a proprietary dependency enabled by default when it works fine without it. In this case even more so because I don't even have a Nvidia card. To be fair I'm just assuming `nvidia-cg-toolkit` won't do anything anyway with alternative GPU manufacturers.

**Comment by jansegre** [comment]
Nvidia's toolkit is exactly needed because you don't have an Nvidia's card.
It is only needed to compile .cg shaders (which is an Nvidia technology
that upstream uses) to .glsl shaders.

And "works fine" is subjective here, because although the main thing works
(which works anyway without a bunch of other default stuff) it is expected
that shaders are available, specially if overlays are available, which
usually work well together.

Anyway, sorry if I heated this conversation.


On Sun, Jan 29, 2017, 10:05 PureTryOut <notifications@github.com> wrote:

It's mainly that I disagree with having a proprietary dependency enabled by
default when it works fine without it. In this case even more so because I
don't even have a Nvidia card. To be fair I'm just assuming
nvidia-cg-toolkit won't do anything anyway with alternative GPU
manufacturers.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/stefan-gr/abendbrot/issues/54#issuecomment-275909597>,
or mute the thread

**Comment by stefan-gr** [comment]
I will evaluate over the next days again if cg is still needed by retroarch to work with the standard shaders. I didn't know nvidia cards can handle them without it.

**Comment by stefan-gr** [comment]
So my findings are as follows:

1. Retroarch hard depends on nvidia-cg-toolkit if someone wants to select *.cg shaders (can't configure without Cg.so, no matter what card is installed)
2. There is no repo with pre-converted glsl shaders (only a buildbot that constantly overwrites the packages)
2. "GLSL shaders are mostly considered a compatibility format.". See https://github.com/libretro/RetroArch/wiki/GLSL-shaders#converting-from-cg-shaders
3. The conversion happening in common-shaders[-cg] results in 66 failures

See:
```
/usr/share/libretro/shaders/xbr/shaders/xbr-mlv4-multipass/xbr-mlv4-pass4.glsl ... failed!
/usr/share/libretro/shaders/xbr/shaders/xbr-mlv4-multipass/xbr-mlv4-pass3.glsl ... failed!
/usr/share/libretro/shaders/xbr/shaders/xbr-lv3-multipass/xbr-lv3-pass1.glsl ... failed!
/usr/share/libretro/shaders/xbr/shaders/xbr-lv2-multipass/xbr-lv2-pass1.glsl ... failed!
/usr/share/libretro/shaders/xbr/shaders/xbr-lv2-multipass/xbr-lv2-noblend-pass1.glsl ... failed!
/usr/share/libretro/shaders/xbr/shaders/legacy/3xbr-v2.1.glsl ... failed!
/usr/share/libretro/shaders/test/lab/xbr/2xbr-lv3-pass1.glsl ... failed!
/usr/share/libretro/shaders/test/lab/xbr/2xbr-lv1-pass1.glsl ... failed!
/usr/share/libretro/shaders/sharpen/shaders/adaptive-sharpen-pass2.glsl ... failed!
/usr/share/libretro/shaders/motionblur/shaders/feedback.glsl ... failed!
/usr/share/libretro/shaders/handheld/shaders/lcd_cgwg/lcd-grid-v2-nvidia.glsl ... failed!
/usr/share/libretro/shaders/handheld/shaders/lcd-shader/backup/lcd-pass-1.glsl ... failed!
/usr/share/libretro/shaders/handheld/shaders/lcd-shader/backup/lcd-pass-0.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/snes-hires-blend.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-aperture.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-royale/src/crt-royale-scanlines-horizontal-apply-mask.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-royale/src/crt-royale-scanlines-horizontal-apply-mask-intel.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-royale/src/crt-royale-scanlines-horizontal-apply-mask-fake-bloom.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-royale/src/crt-royale-scanlines-horizontal-apply-mask-fake-bloom-intel.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-royale/src/crt-royale-brightpass.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-royale/src/crt-royale-bloom-horizontal-reconstitute.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-royale/src/crt-royale-bloom-approx.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-royale/src/crt-royale-bloom-approx-intel.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-royale/src/crt-royale-bloom-approx-fake-bloom.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-royale/src/crt-royale-bloom-approx-fake-bloom-intel.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-lottes-multipass/horz7plus1.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-lottes-multipass/horz7minus1.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-lottes-multipass/horz7.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-lottes-multipass/horz5plus2.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-lottes-multipass/horz5minus2.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-lottes-multipass/horz5.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-lottes-multipass/horz3plus1.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-lottes-multipass/horz3minus1.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-lottes-multipass/horz3.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-lottes-multipass/crt-lottes-multipass.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/crt-interlaced-halation/crt-interlaced-halation-pass2.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/GTU-famicom/scaleY_lite.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/GTU-famicom/scaleY.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/GTU-famicom/scaleX_lite.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/GTU-famicom/scaleX.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/GTU-famicom/lowPass_lite.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/GTU-famicom/lowPass.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/GTU-famicom/combFilter_lite.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/GTU-famicom/combFilter.glsl ... failed!
/usr/share/libretro/shaders/crt/shaders/GTU-famicom/DAC.glsl ... failed!
/usr/share/libretro/shaders/borders/resources/bigblur-2560x1600.glsl ... failed!
/usr/share/libretro/shaders/borders/resources/bigblur-2160p.glsl ... failed!
/usr/share/libretro/shaders/borders/resources/bigblur-1440p.glsl ... failed!
/usr/share/libretro/shaders/borders/resources/bigblur-1080p.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur8x8shared.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur8x8shared-last-pass.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur8x8shared-last-pass-gamma-encode-every-fbo.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur8x8shared-gamma-encode-every-fbo.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur6x6shared.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur6x6shared-last-pass.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur6x6shared-last-pass-gamma-encode-every-fbo.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur6x6shared-gamma-encode-every-fbo.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur12x12shared.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur12x12shared-last-pass.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur12x12shared-last-pass-gamma-encode-every-fbo.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur12x12shared-gamma-encode-every-fbo.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur10x10shared.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur10x10shared-last-pass.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur10x10shared-last-pass-gamma-encode-every-fbo.glsl ... failed!
/usr/share/libretro/shaders/blurs/blur10x10shared-gamma-encode-every-fbo.glsl ... failed!
/usr/share/libretro/shaders/3dfx/shaders/3dfx_pass_2.glsl ... failed!
```

To be frank, I will not remove nvidia-cg-toolkit as a standard dependency in light of my findings, sorry.

**Comment by stefan-gr** [comment]
I forgot to add:
5. games-emulation/common-shaders[-cg] needs nvidia-cg-toolkit for the conversion at build time.

If you don't want this dependency then please set games-emulation/* -cg. But don't forget that some shaders will not work at all in that case.
As soon as upstream changes their policy and shaders I will reflect this in the ebuilds accordingly.

**Comment by stefan-gr** [comment]
Upstream changed their policy and now provide hand curated glsl shaders in a new repo. The shader directory is now filled with glsl shaders, this works without Cg or any gles/egl dependencies and thus no proprietary code on the machine.
