### ISSUE TITLE
Missing Art (Thumbnails, Boxart)

### ISSUE THREAD

**Issue by allanin** [stefan-gr/abendbrot#75]
Without the ability to download from RetroArch the Portage system of Gentoo could provide this functionality.

What about creating a Meta-Ebuild, which uses the flags which already used by emulators?

We would also need for each Boxart an ebuild.

**Comment by stefan-gr** [comment]
Hi,
retroarch can download thumbnails and content through the online updater without issues, since the PATH`s defaults to user writable directories.

The reason I didn't write ebuilds for them is because upstream doesn't provide release version information for the archives which results in random hash changes. Portage refuses to install an ebuild if the checksums don't match, making them useless for users after a while.

I though of using the github repository instead but it's too big and I aborted the download after 500MB with no end in sight. I did not find a way to only fetch specific folders/files so it would bloat the distfiles directory really fast.

The only solution I see for this is hosting the archives ourselves somewhere or bugging upstream until they choose to rewrite the content downloader.

With this I will have to refuse #76, sorry.

I should patch the menu and .cfg file according to USE, so that only menus that are actually expected to work are displayed.
I will write that into my TODO list for the retroarch ebuild rewrite. I have no clue when I come around to do it.

Please continue to  send PR request if you find something you wish to change. I will integrate everything into the rewrite of it.

Thanks for your support.
