### ISSUE TITLE
abendbrot does not exist? Am I doing something wrong?

### ISSUE THREAD

**Issue by kenny-wettlaufer** [stefan-gr/abendbrot#88]
sudo layman -a abendbrot

 * Adding overlay...
 * Warning: an installed db file was not found at: ['/var/lib/layman/cache_930c3ed4a5f89f74fd810585751a06e3.xml']
 * Exception: Overlay "abendbrot" does not exist.

 * CLI: Errors occurred processing action add
 * Exception: Overlay "abendbrot" does not exist.

ooooooohhhh, I didn't compile with the portage extension thing. Sorry, I just started learning Gentoo.
I think that's got to be the issue. It wouldn't add another overlay I found so I guess this is why.

**Comment by stefan-gr** [comment]
Hi,
sorry for the confusing instructions.
There are three ways to install overlays nowadays. with layman[-sync-plugin-portage], with layman[sync-plugin-portage] and straight with portage trough a /etc/portage/repos.conf/overlays.conf file. layman generates a layman.conf for you when [sync-plugin-portage] is set. Otherwise you must source layman in make.conf. I will make the instructions more clear with an example abendbrot.conf file
